# Pre Production & UAT Pipeline
# Deploy pre production or uat env & destroy stages with authorisation
# Author: Dan Rios
trigger: none

variables:
- group: alz
- name: azureServiceConnection
  value: 'spn-azdo-bicep-mgmt'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UATDeploy
  displayName: UAT Deploy
  jobs: 
  - job: whatIfUAT
    displayName: UAT environment what if
    steps:
      - task: AzureCLI@2
        displayName: UAT environment what f
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            name=UATDeploy$(date +%F_%H-%M-%S)
            az account set --subscription $(uatSub)
            az deployment sub what-if -n $name -l $(region) -f '.\alz_workloads\uat\main.bicep' -p '.\alz_workloads\uat\uat.bicepparam'
  - job: waitForValidation
    dependsOn: whatIfUAT
    displayName: Wait for approval
    pool: server  
    timeoutInMinutes: 60 # job times out in 1 hour, allows for running completely headless
    steps:   
    - task: ManualValidation@0
      timeoutInMinutes: 60 # task times out in 1 hour
      inputs:
          # notifyUsers: |
          #     someone@example.com
          instructions: 'Please validate the what-if output and resume'
          onTimeout: 'resume'
  - deployment: UATDeploy
    displayName: Deploy UAT environment
    dependsOn: waitForValidation
    environment: 'UAT'
    strategy: 
      runOnce:
        deploy:
          steps:
           - checkout: self
           - task: AzureCLI@2
             displayName: Deploy UAT
             inputs:
                azureSubscription: $(azureServiceConnection) 
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  name=UATDeploy$(date +%F_%H-%M-%S)
                  az account set --subscription $(uatSub)
                  az deployment sub create -n $name -l $(region) -f '.\alz_workloads\uat\main.bicep' -p '.\alz_workloads\uat\uat.bicepparam'
- stage: UATDestroy
  displayName: UAT Destroy
  dependsOn: UATDeploy
  jobs: 
  - deployment: UATDestroy 
    displayName: Destroy UAT environment
    environment: UAT
    strategy: 
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              displayName: Destroy UAT environment
              inputs:
                azureSubscription: $(azureServiceConnection)
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  for rg in `az group list --query "[? contains(name,'rg-uks-uat-rios-blah')][].{name:name}" -o tsv`; do  for rg in `az group list --query "[].name" -o tsv`; do 
                  ##[command] echo deleting ${rg}
                  az group delete -n ${rg} --yes --no-wait


- stage: PreprodDeploy
  displayName: Pre Prod Deploy
  dependsOn: UATDestroy
  jobs: 
  - job: whatIfPreprod
    displayName: Pre prod environment what if
    steps:
     - task: AzureCLI@2
       displayName: Pre prod connectivity what if
       inputs:
         azureSubscription: $(azureServiceConnection)
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: |
           name=UATDeploy$(date +%F_%H-%M-%S)
           az account set --subscription $(connectivitySub)
           az deployment sub what-if -n $name -l $(region) -f '.\alz_workloads\preprod\main_connectivity.bicep' -p '.\alz_workloads\preprod\uat_connectivity.bicepparam'
     - task: AzureCLI@2
       displayName: Pre prod environment what if
       inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            name=UATDeploy$(date +%F_%H-%M-%S)
            az account set --subscription $(preProdSub)
            az deployment sub what-if -n $name -l $(region) -f '.\alz_workloads\preprod\main.bicep' -p '.\alz_workloads\preprod\uat.bicepparam'
  - job: waitForValidation
    dependsOn: whatIfPreprod
    displayName: Wait for approval
    pool: server  
    timeoutInMinutes: 60 # job times out in 1 hour, allows for running completely headless
    steps:   
    - task: ManualValidation@0
      timeoutInMinutes: 60 # task times out in 1 hour
      inputs:
          # notifyUsers: |
          #     someone@example.com
          instructions: 'Please validate the what-if output and resume'
          onTimeout: 'resume'

  - deployment: PreprodDeploy
    displayName: Deploy Pre Production Environment
    dependsOn: waitForValidation
    environment: Preprod
    strategy: 
      runOnce:
        deploy:
          steps:
           - checkout: self
           - task: AzureCLI@2
             displayName: Pre prod connectivity deploy
             inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                name=preprodDeploy$(date +%F_%H-%M-%S)
                az account set --subscription $(connectivitySub)
                az deployment sub create -n $name -l $(region) -f '.\alz_workloads\preprod\main_connectivity.bicep' -p '.\alz_workloads\preprod\preprod_connectivity.bicepparam'
           - task: AzureCLI@2
             displayName: Pre production environment deploy 
             inputs:
                azureSubscription: $(azureServiceConnection)
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  name=PreprodDeploy$(date +%F_%H-%M-%S)
                  az account set --subscription $(preProdSub)
                  az deployment sub create -n $name -l $(region) -f '.\alz_workloads\preprod\main.bicep' -p '.\alz_workloads\preprod\preprod.bicepparam'

- stage: PreprodDestroy
  displayName: Pre Prod Destroy
  dependsOn: PreprodDeploy
  jobs: 
  - deployment: PreprodDestroy 
    displayName: Destroy pre prod connectivity environment
    environment: Preprod
    strategy: 
      runOnce:
        deploy:
          steps:
            - task: AzureCLI@2
              displayName: Destroy pre prod connectivity
              inputs:
                azureSubscription: $(azureServiceConnection) 
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  name=PreprodDestroy$(date +%F_%H-%M-%S)
                  az account set --subscription $(connectivitySub)
                  az deployment group create --mode Complete -n $name -g rg-uks-preprod-rios-prod -f .\.scripts\destroyARM.json

            - task: AzureCLI@2
              displayName: Destroy pre prod subscription enviornment 
              inputs:
                azureSubscription: $(azureServiceConnection) 
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  for rg in `az group list --query "[].name" -o tsv`; do 
                  ##[command] echo deleting ${rg}
                  az group delete -n ${rg} --yes --no-wait
